version: 2
mergeable:
- when: pull_request.*, pull_request_review.*
  validate:
  - do: label
    must_include:
       regex: 'testing'
       regex_flag: 'none' # Optional. Specify the flag for Regex. default is 'i', to disable default use 'none'
       message: 'testing label is mandatory'

